# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
np.random.random(((3,3,3)))

array([[[0.29210446, 0.73854883, 0.70693508],
        [0.31156406, 0.28019999, 0.64542497],
        [0.98552253, 0.42641299, 0.55850103]],

       [[0.97342632, 0.65780107, 0.04157007],
        [0.40855987, 0.25950704, 0.15202075],
        [0.94468453, 0.00354824, 0.04294842]],

       [[0.40782566, 0.78794337, 0.53940721],
        [0.85395414, 0.70101548, 0.45639253],
        [0.44551728, 0.49009252, 0.4182681 ]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [5]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 1.81306595 -1.5519519   0.59356225 -1.47508439 -0.84245352]
 [ 1.13944612 -0.8334077  -0.32167675 -0.9064745   0.51307749]
 [-1.40401694  1.1293716   0.41574924 -0.31792413  0.26020393]
 [-0.84809864  0.59705075  1.42080685  0.7831269  -0.79488914]
 [-0.13505867 -1.15165919  1.41944765 -0.60952468  1.10731142]]


# 5.  How to find common values between two arrays?

In [6]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [9]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print (yesterday)
print (today)
print (tomorrow)

2020-07-25
2020-07-26
2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [10]:
a=np.random.random((5))
b=np.random.random((5))
print(np.intersect1d(a, b))

[]


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [11]:
z=np.random.rand(10)
p=z.max()
z[z.argmax()]=0
print (p)
print (z)

0.9039337136215955
[0.827061   0.6338872  0.12134923 0.18538461 0.22929832 0.50895027
 0.4522244  0.63078443 0.17996916 0.        ]


# 9. How to print all the values of an array?

In [12]:


Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [13]:
X = np.random.rand(5, 10)



print (X.mean(axis=1))
print (X)
Y = X - (X.mean(axis=1, keepdims=True))
print (Y)

[0.48499887 0.58150348 0.48657656 0.65970583 0.58605206]
[[3.86170015e-01 7.44959455e-01 4.34592710e-04 8.04264664e-01
  4.31982738e-01 8.90195638e-01 1.27631306e-03 7.36225187e-02
  5.39551078e-01 9.77531674e-01]
 [6.29854596e-01 5.29320017e-01 3.40310247e-01 8.93194284e-01
  1.20455685e-01 8.70232346e-01 7.92946876e-01 8.74037442e-01
  7.03287254e-01 6.13960304e-02]
 [1.84242969e-01 1.03104433e-01 9.61152906e-01 5.19282593e-01
  3.88344619e-01 5.66648772e-02 9.53750667e-01 7.65321516e-01
  6.76570279e-01 2.57330767e-01]
 [5.28316703e-01 8.84048574e-01 8.47747116e-02 6.19487604e-01
  4.88091317e-01 7.50226936e-01 9.79667847e-01 7.22744892e-01
  8.46943366e-01 6.92756304e-01]
 [5.37628327e-01 1.57903732e-01 6.70969760e-02 9.48174259e-01
  6.33902003e-01 8.28520724e-01 8.71041226e-01 8.27692980e-01
  8.65270683e-01 1.23289730e-01]]
[[-0.09882885  0.25996059 -0.48456428  0.3192658  -0.05301613  0.40519677
  -0.48372256 -0.41137635  0.05455221  0.49253281]
 [ 0.04835112 -0.05218346 -0.241

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [14]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 3. 1. 1. 4. 1. 7. 4. 1. 4.]


# 12.How to get the diagonal of a dot product?

In [15]:
A=np.array(([
    [1,2,3],[4,5,6],[7,8,9]
    
]))

B=np.array(([
    [7,8,9],[4,5,6],[1,2,3]
    
]))

Z=np.diag(np.dot(A,B))

print (np.diag(A))

print (np.diag(B))

print ("Diagonal Dot Operation of two Vectors")

print (Z)

[1 5 9]
[7 5 3]
Diagonal Dot Operation of two Vectors
[ 18  69 138]


# 13.How to find the most frequent value in an array?

In [16]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())
print (Z)

2
[0 9 9 2 1 2 2 4 2 0 1 3 8 4 7 5 5 0 6 3 7 5 2 2 0 2 4 6 6 5 1 9 0 2 0 4 7
 7 5 4 4 2 3 4 9 0 4 1 0 1]


# 14.How to get the n largest values of an array

In [17]:
# Z = np.arange(10000)
# np.random.shuffle(Z)
Z=np.random.randint(0,100,30)
n = 5
print (Z)


print (np.sort(Z))
print (Z[np.argsort(Z)[-n:]])


[59 67 86 95 70 43 72 43 87  7  0 29 98 62 13 88 91 70 73 20 30 39 98 95
 75 19 14 41 33 24]
[ 0  7 13 14 19 20 24 29 30 33 39 41 43 43 59 62 67 70 70 72 73 75 86 87
 88 91 95 95 98 98]
[91 95 95 98 98]


# 15.How to create a record array from a regular array?

In [18]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print (result)

[(1, 'Red', 12.2) (2, 'Green', 15. ) (3, 'White', 20. )
 (4, 'Orange', 40. )]
